
path: /home/oeljungg/Documents/Groupwork/YOLOv8 #/datasets/tdt4265/ad/NAPLab-LiDAR (total path!)
train: data/train/images
val: data/test/images
test: data/test/images

task: detect
mode: train
model: runs/detect/train8/weights/best.pt
data: config.yaml


# Classes:
names: 
  0: car
  1: truck
  2: bus
  3: motorcycle
  4: bicycle
  5: scooter
  6: person
  7: rider



# hyperparameters  
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
optimizer: "SGD"